services:
  db:
    image: mysql:8.0
    container_name: db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./meu_bolso-db/db-init:/docker-entrypoint-initdb.d
    #command: --default-authentication-plugin=mysql_native_password
    networks:
      - minha_rede
    
  api:
    build:
      context: ./meu_bolso-api
    container_name: api_container
    ports:
      - "8000:8000"  # Porta que sua API irá expor
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - minha_rede

#  frontend:
#    build:
#      context: ./meu_bolso-frontend # O caminho para a pasta do seu projeto frontend
#    container_name: frontend_container
#    ports:
#      - "3000:3000"  # A porta onde o frontend será exposto
#    environment:
#      - VUE_APP_API_URL=http://api:8000 # URL interna para acessar a API
#    depends_on:
#      - api
#    networks:
#      - minha_rede

networks:
  minha_rede:
    driver: bridge